In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [3]:
firecalls = pd.read_csv('./Seattle_Real_Time_Fire_911_Calls.csv')

/Users/emilygeller/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
len(firecalls.Type.unique())

188

In [5]:
firecalls = firecalls.drop(0)

In [6]:
firecalls.Datetime[1]

'11/09/2011 11:33:00 PM +0000'

In [7]:
from dateutil import parser
parsed_date = parser.parse(firecalls.Datetime[1])

In [8]:
firecalls['Datetime'] = firecalls.Datetime.str.replace(r'\+.*','')

In [9]:
from datetime import datetime
from tqdm import tqdm

In [10]:
datetime.strptime(firecalls.Datetime[1], '%m/%d/%Y %I:%M:%S %p ')

datetime.datetime(2011, 11, 9, 23, 33)

In [11]:
for key, value in tqdm(firecalls.Datetime.head().iteritems()):
    print(key, value)

5it [00:00, 6061.13it/s]

1 11/09/2011 11:33:00 PM
2 11/09/2011 11:32:00 PM
3 11/09/2011 11:32:00 PM
4 11/09/2011 11:29:00 PM
5 11/09/2011 11:25:00 PM

In [12]:
firecalls.Datetime.shape

(698377,)

In [13]:
'11/09/2011T11:33:00 PM '.replace('T',' ')

'11/09/2011 11:33:00 PM '

In [ ]:

for key, date in tqdm(firecalls.Datetime.iteritems()):
    try:
        firecalls.loc[key,'dt'] = datetime.strptime(date,'%m/%d/%Y %I:%M:%S %p ')
    except:
        pass

33602it [03:40, 152.20it/s]

In [ ]:
strings.to_csv('datetime_strings')
datetimes.to_csv('cleaned_datetimes')

In [17]:
datetimes

                      date
446402 2015-08-16 02:40:00
293401 2014-01-16 03:55:00
626165 2017-07-04 02:52:00
461210 2015-10-08 10:41:00
219188 2013-03-23 08:04:00
291485 2014-01-09 02:45:00
185871 2012-11-02 13:57:00
373334 2014-11-16 01:04:00
527148 2016-06-07 15:48:00
278606 2013-11-14 16:13:00
278464 2013-11-14 06:46:00
394411 2015-02-08 19:54:00
274373 2013-10-24 20:33:00
416402 2015-05-04 19:45:00
642160 2017-08-26 13:19:00
549344 2016-08-22 23:53:00
548653 2016-08-21 08:38:00
148941 2012-06-03 21:01:00
111283 2011-12-16 17:59:00
450971 2015-08-31 22:36:00
266325 2013-09-21 17:59:00
177934 2012-09-29 09:11:00
102315 2010-07-05 07:39:00
128203 2012-03-05 01:51:00
564517 2016-10-15 12:39:00
451843 2015-09-03 20:28:00
112280 2011-12-21 14:15:00
262619 2013-09-06 09:19:00
493811 2016-02-08 10:51:00
280991 2013-11-24 22:19:00
460943 2015-10-08 10:45:00
124600 2012-02-16 17:58:00
650269 2017-09-22 08:09:00
559845 2016-09-28 10:23:00
87511  2010-09-25 07:49:00
44675  2011-05-06 09:48:00
467652 2015-10-30 20:01:00
536781 2016-07-12 03:28:00
291173 2014-01-07 21:20:00
358993 2014-09-25 20:37:00
383803 2014-12-28 04:23:00
262789 2013-09-07 01:14:00
611622 2017-05-17 12:31:00
520464 2016-05-14 06:15:00
329210 2014-06-10 16:02:00
438510 2015-07-21 16:31:00
112389 2011-12-22 01:07:00
175786 2012-09-20 05:55:00
492866 2016-02-04 17:22:00
592040 2017-03-06 00:50:00
44276  2011-05-08 04:02:00
528609 2016-06-13 00:09:00
618205 2017-06-08 11:06:00
307909 2014-03-16 07:53:00
685581 2018-01-29 01:10:00
158587 2012-07-13 17:00:00
41827  2011-05-19 16:22:00
465519 2015-10-23 20:15:00
318273 2014-04-27 22:18:00
551486 2016-08-29 10:45:00
377949 2014-12-05 16:59:00
286141 2013-12-16 06:33:00
480895 2015-12-20 09:12:00
606430 2017-04-27 13:18:00
221173 2013-03-31 03:23:00
556130 2016-09-13 23:34:00
518502 2016-05-09 20:06:00
685181 2018-01-26 19:12:00
630556 2017-07-19 06:52:00
584671 2016-12-27 08:26:00
185814 2012-11-02 03:15:00
663926 2017-11-11 07:53:00
387739 2015-01-13 05:56:00
278026 2013-11-12 05:39:00
475976 2015-12-05 08:33:00
633160 2017-07-27 21:32:00
248392 2013-07-13 20:36:00
131554 2012-03-20 16:06:00
324570 2014-05-23 14:02:00
231617 2013-05-12 15:07:00
522327 2016-05-22 23:45:00
447823 2015-08-21 21:50:00
212951 2013-02-25 08:52:00
467710 2015-11-04 06:23:00
523152 2016-05-25 07:32:00
640352 2017-08-21 00:25:00
67125  2011-01-12 16:26:00
500637 2016-03-04 21:39:00
62359  2011-02-05 05:32:00
691659 2018-02-18 11:12:00
61381  2011-02-11 12:40:00
671541 2017-12-07 21:33:00
219305 2013-03-23 01:54:00
533445 2016-06-28 20:42:00
73479  2010-12-12 12:13:00
318918 2014-04-30 10:24:00
58641  2011-02-24 14:13:00
364291 2014-10-15 21:42:00
567549 2016-10-25 21:28:00
105905 2011-11-21 20:36:00
51797  2011-04-01 21:05:00
457715 2015-09-26 00:31:00
272767 2013-10-17 01:17:00
254677 2013-08-06 22:13:00
107422 2011-11-27 21:59:00
561156 2016-10-04 22:27:00
11607  2011-10-02 04:45:00
553163 2016-09-04 09:41:00
170759 2012-08-31 12:08:00
344433 2014-08-04 02:54:00
544617 2016-08-06 02:48:00
151700 2012-06-15 15:33:00
415266 2015-05-02 15:46:00
692770 2018-02-24 06:39:00
288816 2013-12-26 00:43:00
418669 2015-05-13 16:34:00
606861 2017-04-28 10:37:00
506403 2016-03-25 10:32:00
527664 2016-06-09 00:02:00
55247  2011-03-16 07:16:00
608237 2017-05-04 21:56:00
202388 2013-01-11 20:11:00
181033 2012-10-12 00:45:00
591628 2017-03-04 13:53:00
692410 2018-02-23 19:51:00
131761 2012-03-21 02:59:00
429653 2015-06-22 18:23:00
106682 2011-11-24 12:32:00
531846 2016-06-25 17:48:00
147736 2012-05-29 18:43:00
655046 2017-10-08 17:30:00
10054  2011-10-03 12:42:00
3486   2011-10-25 12:57:00
431769 2015-06-28 22:45:00
491268 2016-01-29 02:25:00
504813 2016-03-20 17:44:00
366579 2014-10-24 20:39:00
317335 2014-04-24 12:38:00
238055 2013-06-05 00:46:00
205200 2013-01-23 15:18:00
220812 2013-03-30 00:18:00
563509 2016-10-12 03:16:00
425230 2015-06-06 00:57:00
547731 2016-08-18 18:34:00
487197 2016-01-13 02:51:00
201701 2013-01-08 23:37:00
193644 2012-12-06 18:14:00
470036 2015-11-08 08:33:00
14972  2011-09-30 11:34:00
8361   2011-10-04 01:12:00
110840 2011-12-14 18:05:00
87112  2010-09-27 07:31:00
80583  2010-10-27 07:51:00
290680 2014-01-04 02:40:00
471278 2015-11-17 01:07:00
581758 2016-12-16 12:33:00
227191 2013-04-24 21:49:00
395755 2015-02-14 01:19:00
298504 2014-02-07 14:43:00
269728 2013-10-04 10:31:00
401858 2015-03-11 00:22:00
549452 2016-08-23 02:40:00
629173 2017-07-14 15:09:00
634123 2017-07-31 16:18:00
238370 2013-06-06 07:36:00
57242  2011-03-03 05:10:00
408492 2015-04-05 05:43:00
367513 2014-10-28 19:34:00
550709 2016-08-27 22:49:00
412063 2015-04-21 20:02:00
161545 2012-07-26 00:45:00
82130  2010-10-20 07:48:00
314810 2014-04-12 03:54:00
6953   2011-10-08 05:15:00
83089  2010-10-15 07:38:00
541293 2016-07-26 07:03:00
366566 2014-10-24 19:01:00
286569 2013-12-17 18:47:00
342222 2014-07-27 06:00:00
301928 2014-02-19 09:01:00
544853 2016-08-06 15:30:00
80260  2010-10-29 05:00:00
680274 2018-01-10 08:59:00
282046 2013-11-29 22:10:00
561924 2016-10-06 11:42:00
274674 2013-10-25 10:04:00
279995 2013-11-20 16:48:00
475216 2015-11-29 02:37:00
16074  2011-09-29 21:31:00
688623 2018-02-09 04:38:00
632291 2017-07-24 18:06:00
691055 2018-02-16 19:34:00
452787 2015-09-06 23:55:00
338320 2014-07-12 13:29:00
466853 2015-10-28 17:30:00
28400  2011-08-07 11:27:00
552304 2016-09-01 10:43:00
66991  2011-01-13 07:28:00
230894 2013-05-09 00:10:00
430875 2015-06-27 22:08:00
232430 2013-05-14 20:20:00
188999 2012-11-16 08:19:00
352697 2014-09-03 01:16:00
333333 2014-06-25 07:16:00
7403   2011-10-06 12:48:00
240165 2013-06-13 13:01:00
190577 2012-11-23 07:18:00
190861 2012-11-24 20:44:00
558569 2016-09-25 18:16:00
135415 2012-04-06 07:00:00
669974 2017-12-03 18:35:00
369352 2014-11-01 21:34:00
113411 2011-12-27 00:59:00
422928 2015-05-30 00:46:00
25374  2011-08-20 05:06:00
206688 2013-01-30 04:56:00
226364 2013-04-21 06:32:00
514763 2016-04-23 09:11:00
397141 2015-02-20 05:40:00
91005  2010-09-09 07:44:00
225558 2013-04-18 04:07:00
99329  2010-07-17 07:54:00
97802  2010-07-24 07:59:00
338302 2014-07-13 02:26:00
426198 2015-06-10 20:16:00
675093 2017-12-20 17:58:00
456059 2015-09-19 20:49:00
128700 2012-03-06 16:34:00
172350 2012-09-06 14:39:00
339748 2014-07-17 22:28:00
260307 2013-08-28 19:17:00
77233  2010-11-24 15:18:00
454045 2015-09-12 11:34:00
430253 2015-06-23 20:44:00
9408   2011-10-03 11:08:00
402989 2015-03-15 12:51:00
38284  2011-06-04 07:47:00
356973 2014-09-18 16:05:00
555328 2016-09-13 04:45:00
457042 2015-09-22 22:24:00
74514  2010-12-07 12:11:00
337635 2014-07-10 05:54:00
229518 2013-05-04 05:39:00
575824 2016-11-24 02:24:00
457108 2015-09-22 22:07:00
475165 2015-11-29 18:39:00
129270 2012-03-08 22:05:00
673628 2017-12-16 10:12:00
637072 2017-08-08 20:05:00
198481 2012-12-26 09:29:00
569931 2016-11-03 09:53:00
408295 2015-04-05 22:05:00
465860 2015-10-25 04:12:00
224785 2013-04-14 14:48:00
146507 2012-05-24 05:07:00
332472 2014-06-23 01:39:00
653438 2017-10-04 23:54:00
616556 2017-06-02 08:44:00
39724  2011-05-28 23:03:00
406751 2015-03-29 14:40:00
240088 2013-06-12 19:41:00
339507 2014-07-17 01:14:00
124899 2012-02-17 18:08:00
399083 2015-02-27 18:08:00
647183 2017-09-12 22:40:00
575926 2016-11-24 20:05:00
482176 2015-12-24 02:19:00
88109  2010-09-22 22:00:00
407058 2015-03-31 17:25:00
624715 2017-06-29 22:53:00
43462  2011-05-12 04:06:00
315034 2014-04-17 00:18:00
220878 2013-04-01 09:56:00
567664 2016-10-27 18:13:00
253627 2013-08-02 20:23:00
450611 2015-08-29 23:23:00
350793 2014-08-26 20:50:00
473152 2015-11-21 16:16:00
523827 2016-05-27 08:14:00
262257 2013-09-05 01:00:00
391805 2015-01-29 10:26:00
568075 2016-10-27 04:14:00
140919 2012-04-30 17:30:00
645212 2017-09-05 00:58:00
177993 2012-09-29 04:48:00
413072 2015-04-23 14:27:00
532017 2016-06-25 23:14:00
464443 2015-10-18 18:24:00
78312  2010-11-20 12:23:00
71702  2010-12-21 04:30:00
677966 2017-12-31 19:12:00
545020 2016-08-08 03:35:00
89914  2010-09-14 07:43:00
54675  2011-03-18 22:15:00
518168 2016-05-10 01:02:00
263026 2013-09-07 22:32:00
166600 2012-08-14 19:53:00
269232 2013-10-02 17:54:00
331965 2014-06-20 04:43:00
532715 2016-06-26 23:37:00
130948 2012-03-16 23:39:00
165005 2012-08-08 19:27:00
178676 2012-10-02 17:03:00
175376 2012-09-18 20:26:00
7331   2011-10-06 11:27:00
60853  2011-02-13 11:06:00
42982  2011-05-14 08:41:00
313505 2014-04-08 11:24:00
151844 2012-06-16 03:05:00
247248 2013-07-09 20:16:00
188489 2012-11-15 20:20:00
515147 2016-04-24 15:01:00
657049 2017-10-15 11:57:00
206445 2013-01-28 23:38:00
396124 2015-02-17 08:43:00
230937 2013-05-09 04:24:00
523385 2016-05-25 01:33:00
387764 2015-01-14 08:08:00
122670 2012-02-09 02:16:00
556014 2016-09-16 21:47:00
394314 2015-02-07 15:41:00
353682 2014-09-06 09:11:00
533697 2016-06-30 06:25:00
483772 2015-12-31 07:09:00
593603 2017-03-11 19:59:00
229502 2013-05-04 02:34:00
260939 2013-08-31 01:55:00
88316  2010-09-22 04:00:00
304653 2014-03-03 08:53:00
173658 2012-09-11 17:08:00
498051 2016-02-25 17:00:00
509724 2016-04-05 06:32:00
1348   2011-11-03 20:23:00
8312   2011-10-04 01:50:00
385991 2015-01-05 21:16:00
178915 2012-10-02 21:51:00
653052 2017-10-03 09:00:00
291870 2014-01-10 07:52:00
520913 2016-05-15 22:30:00
283363 2013-12-07 15:41:00
382731 2014-12-25 23:53:00
377146 2014-12-02 05:31:00
697445 2018-03-10 02:14:00
52787  2011-03-27 21:13:00
309595 2014-03-23 21:00:00
517717 2016-05-04 21:03:00
135878 2012-04-07 21:01:00
687906 2018-02-04 16:25:00
354778 2014-09-10 09:31:00
272792 2013-10-17 03:21:00
620340 2017-06-16 08:37:00
375322 2014-11-23 21:27:00
110881 2011-12-14 21:04:00
450019 2015-08-28 22:25:00
430664 2015-06-24 22:58:00
420321 2015-05-20 00:41:00
383504 2014-12-27 00:43:00
572138 2016-11-10 21:45:00
644729 2017-09-05 07:56:00
131955 2012-03-22 02:46:00
180174 2012-10-08 20:15:00
180389 2012-10-09 13:23:00
352856 2014-09-03 14:37:00
96441  2010-08-04 07:50:00
115761 2012-01-07 03:14:00
453545 2015-09-10 04:52:00
80344  2010-10-28 07:53:00
11898  2011-10-02 01:14:00
623819 2017-06-27 04:18:00
490031 2016-01-24 06:29:00
568096 2016-10-28 17:30:00
213837 2013-03-01 06:33:00
210460 2013-02-15 04:34:00
290802 2014-01-05 00:58:00
307065 2014-03-12 20:45:00
188333 2012-11-13 08:36:00
493219 2016-02-05 14:55:00
560334 2016-09-30 16:22:00
265039 2013-09-16 03:55:00
27273  2011-08-12 02:33:00
589291 2017-01-10 20:55:00
347365 2014-08-13 18:17:00
249754 2013-07-18 21:57:00
87338  2010-09-26 07:27:00
256358 2013-08-13 07:08:00
486227 2016-01-12 22:36:00
682616 2018-01-20 02:28:00
577472 2016-12-01 09:34:00
107832 2011-11-30 00:32:00
23470  2011-08-27 20:01:00
639689 2017-08-18 08:06:00
237080 2013-06-01 02:30:00
239459 2013-06-10 19:45:00
539198 2016-07-19 20:35:00
142823 2012-05-08 19:44:00
149181 2012-06-04 19:09:00
560098 2016-09-29 02:39:00
575675 2016-11-23 23:26:00
525983 2016-06-02 11:08:00
486890 2016-01-10 21:45:00
606199 2017-04-25 19:56:00
151321 2012-06-14 02:36:00
506869 2016-03-26 21:57:00
305641 2014-03-07 13:23:00
434448 2015-07-07 23:07:00
105780 2011-11-19 23:16:00
604903 2017-04-21 10:00:00
654485 2017-10-07 18:33:00
59161  2011-02-21 14:32:00
341222 2014-07-21 20:01:00
547709 2016-08-16 09:50:00
306105 2014-03-09 16:28:00
589195 2017-01-10 16:53:00
303002 2014-02-24 06:58:00
241481 2013-06-18 04:32:00
196740 2012-12-18 23:05:00
212586 2013-02-24 16:36:00
545358 2016-08-09 16:55:00
388344 2015-01-18 00:51:00
670478 2017-12-02 01:06:00
250340 2013-07-21 07:28:00
249461 2013-07-17 19:26:00
176010 2012-09-21 02:57:00
84398  2010-10-09 07:31:00
320710 2014-05-07 00:30:00
139288 2012-04-23 17:26:00
484936 2016-01-04 19:14:00
165435 2012-08-10 04:17:00
683840 2018-01-22 09:37:00
406545 2015-03-29 00:19:00
311090 2014-03-29 21:09:00
279211 2013-11-17 17:43:00
647478 2017-09-13 16:29:00
675367 2017-12-20 15:19:00
19969  2011-09-11 19:55:00
352497 2014-09-01 23:23:00
455149 2015-09-16 07:55:00
135838 2012-04-07 19:53:00
335556 2014-07-03 05:17:00
97466  2010-07-27 07:40:00
538591 2016-07-17 00:28:00
331718 2014-06-20 00:27:00
470516 2015-11-11 00:08:00
587706 2017-01-06 06:11:00
264341 2013-09-13 02:16:00
123293 2012-02-10 03:11:00
89853  2010-09-14 13:00:00
381159 2014-12-17 21:37:00
674555 2017-12-21 14:49:00
660346 2017-10-27 16:00:00
242605 2013-06-22 18:22:00
493499 2016-02-06 20:34:00
231355 2013-05-10 19:01:00
1246   2011-11-04 08:31:00
632213 2017-07-24 07:17:00
24746  2011-08-22 16:29:00
212891 2013-02-25 01:25:00
469272 2015-11-11 00:03:00
435163 2015-07-08 04:17:00
202466 2013-01-11 23:23:00
331467 2014-06-18 21:54:00
622699 2017-06-23 21:20:00
203080 2013-01-14 07:28:00
149415 2012-06-05 20:36:00
634456 2017-08-03 06:00:00
399597 2015-03-02 02:47:00
114336 2011-12-31 08:41:00
422094 2015-05-26 04:35:00
127868 2012-03-05 02:16:00
253664 2013-08-03 01:14:00
307723 2014-03-15 06:09:00
7221   2011-10-06 23:59:00
88956  2010-09-19 12:00:00
656675 2017-10-13 07:32:00
167627 2012-08-18 13:01:00
186707 2012-11-05 23:56:00
629341 2017-07-15 19:12:00
601351 2017-04-08 15:34:00
693476 2018-02-26 00:49:00
411989 2015-04-22 07:27:00
219242 2013-03-22 22:21:00
504225 2016-03-17 23:43:00
438061 2015-07-19 22:02:00
228461 2013-04-30 15:00:00
636433 2017-08-06 16:29:00
290248 2014-01-04 02:27:00
171071 2012-09-01 10:06:00
580367 2016-12-11 11:41:00
270693 2013-10-09 20:43:00
441389 2015-07-30 23:11:00
279588 2013-11-20 13:38:00
630910 2017-07-23 13:21:00
110943 2011-12-15 01:26:00
155766 2012-07-02 12:54:00
155947 2012-07-03 03:13:00
261477 2013-09-02 02:16:00
616824 2017-06-02 20:10:00
109259 2011-12-07 00:17:00
13725  2011-10-01 02:18:00
144101 2012-05-14 00:59:00
51544  2011-04-03 12:04:00
95978  2010-08-06 07:42:00
305067 2014-03-04 16:56:00
408690 2015-04-06 21:48:00
302473 2014-02-21 17:02:00
602540 2017-04-15 05:50:00
91720  2010-08-31 07:43:00
510202 2016-04-06 21:52:00
329257 2014-06-10 18:59:00
253318 2013-08-01 13:01:00
405866 2015-03-26 15:48:00
534168 2016-07-02 03:56:00
305039 2014-03-05 23:10:00
291214 2014-01-07 17:26:00
340875 2014-07-21 05:25:00
482805 2015-12-27 02:53:00
450754 2015-08-30 12:56:00
438520 2015-07-20 10:34:00
348907 2014-08-19 08:59:00
149953 2012-06-08 06:55:00
581424 2016-12-14 14:01:00
573706 2016-11-19 00:20:00
525914 2016-06-02 01:22:00
255312 2013-08-09 02:25:00
561195 2016-10-03 02:01:00
51884  2011-04-01 11:36:00
427170 2015-06-12 07:20:00
542656 2016-07-30 04:18:00
3886   2011-10-23 03:23:00
314874 2014-04-12 19:24:00
457099 2015-09-23 07:48:00
130420 2012-03-13 23:20:00
648677 2017-09-18 09:09:00
386953 2015-01-10 20:10:00
678010 2017-12-30 12:45:00
521440 2016-05-18 01:58:00
367540 2014-10-28 04:33:00
626226 2017-07-04 12:10:00
383440 2014-12-27 17:18:00
118559 2012-01-20 09:26:00
202528 2013-01-12 02:31:00
41800  2011-05-19 19:41:00
57185  2011-03-03 15:09:00
697283 2018-03-10 01:48:00
420121 2015-05-19 02:57:00
228167 2013-04-29 05:55:00
630634 2017-07-20 08:54:00
371125 2014-11-08 03:20:00
290968 2014-01-05 09:29:00
180775 2012-10-10 21:59:00
437490 2015-07-17 03:57:00
172392 2012-09-06 18:39:00
633346 2017-07-28 12:20:00
394306 2015-02-09 14:26:00
268725 2013-09-30 11:16:00
416128 2015-05-04 19:30:00
303590 2014-02-26 23:38:00
62474  2011-02-04 17:35:00
671920 2017-12-10 01:19:00
374614 2014-11-24 15:23:00
174196 2012-09-13 22:05:00
693675 2018-02-25 23:28:00
85238  2010-10-05 07:47:00
258756 2013-08-22 21:58:00
353689 2014-09-06 23:12:00
596508 2017-03-22 01:24:00
276681 2013-11-02 20:13:00
86816  2010-09-28 07:33:00
92877  2010-08-25 07:29:00
103098 2010-07-01 17:00:00
27814  2011-08-09 21:18:00
379269 2014-12-09 20:25:00
43048  2011-05-14 03:17:00
564467 2016-10-15 04:56:00
50277  2011-04-09 05:09:00
237254 2013-06-01 12:09:00
145784 2012-05-21 03:13:00
575003 2016-11-22 17:23:00
178984 2012-10-03 15:36:00
80873  2010-10-26 07:36:00
552886 2016-09-06 14:30:00
290897 2014-01-07 02:04:00
395785 2015-02-13 06:31:00
293130 2014-01-14 23:41:00
483627 2016-01-02 22:13:00
509964 2016-04-06 02:18:00
649555 2017-09-22 21:51:00
132602 2012-03-24 23:59:00
74779  2010-12-05 16:07:00
234971 2013-05-24 02:04:00
556358 2016-09-15 17:30:00
250576 2013-07-22 00:25:00
80300  2010-10-28 16:00:00
523428 2016-05-24 15:16:00
197200 2012-12-20 21:22:00
575986 2016-11-26 21:34:00
393895 2015-02-07 08:05:00
266994 2013-09-25 19:42:00
356461 2014-09-16 02:48:00
622051 2017-06-22 07:33:00
410585 2015-04-12 21:13:00
290052 2014-01-02 19:56:00
311087 2014-03-29 21:05:00
451115 2015-09-01 06:36:00
526427 2016-06-06 16:58:00
242674 2013-06-22 22:47:00
99092  2011-11-10 19:30:00
412000 2015-04-20 19:22:00
421952 2015-05-25 11:02:00
56849  2011-03-05 01:12:00
519876 2016-05-11 20:06:00
621151 2017-06-18 15:14:00
155174 2012-06-29 23:54:00
637395 2017-08-13 04:14:00
596701 2017-03-22 08:30:00
601511 2017-04-09 04:26:00
112855 2011-12-24 03:11:00
325586 2014-05-27 20:38:00
137853 2012-04-16 20:13:00
409095 2015-04-08 03:38:00
265129 2013-09-16 11:46:00
384074 2014-12-30 17:11:00
325453 2014-05-27 16:34:00
414112 2015-04-28 07:15:00
583986 2016-12-21 19:49:00
441434 2015-07-31 09:10:00
43454  2011-05-12 04:45:00
535544 2016-07-07 01:37:00
616779 2017-06-03 01:24:00
40520  2011-05-25 04:55:00
461331 2015-10-08 17:30:00
42230  2011-05-17 21:38:00
369232 2014-11-01 16:49:00
51489  2011-04-03 05:22:00
472310 2015-11-18 08:44:00
374566 2014-11-23 18:06:00
127654 2012-03-01 19:48:00
208271 2013-02-05 19:07:00
319016 2014-04-30 23:40:00
352250 2014-08-31 20:55:00
347779 2014-08-14 06:31:00
223176 2013-04-08 08:35:00
228746 2013-05-01 14:12:00
71285  2010-12-23 09:06:00
600809 2017-04-08 02:13:00
431035 2015-06-28 07:53:00
457472 2015-09-24 20:00:00
423116 2015-05-31 01:18:00
140665 2012-04-29 14:25:00
294003 2014-01-18 09:39:00
607853 2017-05-03 14:57:00
6705   2011-10-09 06:04:00
365827 2014-10-21 20:36:00
169126 2012-08-24 20:31:00
362907 2014-10-10 16:52:00
181396 2012-10-14 01:24:00
464490 2015-10-19 06:52:00
510888 2016-04-15 17:22:00
167043 2012-08-16 14:12:00
554101 2016-09-05 23:01:00
545676 2016-08-10 06:19:00
260649 2013-08-29 21:12:00
214775 2013-03-04 23:07:00
281808 2013-11-29 10:01:00
55095  2011-03-17 01:28:00
228602 2013-04-30 20:02:00
20136  2011-09-11 03:44:00
508455 2016-04-02 22:31:00
483542 2016-01-01 12:57:00
578266 2016-12-05 11:21:00
683092 2018-01-18 21:58:00
518621 2016-05-06 22:20:00
574815 2016-11-20 01:50:00
649121 2017-09-23 06:05:00
285357 2013-12-11 21:55:00
236838 2013-05-30 14:36:00
92437  2010-08-27 18:00:00
218377 2013-03-19 08:18:00
500825 2016-03-05 13:43:00
336410 2014-07-05 13:52:00
421577 2015-05-23 12:16:00
696058 2018-03-06 13:08:00
277161 2013-11-08 20:01:00
228321 2013-04-29 08:55:00
181506 2012-10-14 18:22:00
203904 2013-01-18 01:32:00
99040  2010-07-18 15:00:00
137471 2012-04-16 07:52:00
79541  2010-11-01 07:24:00
249343 2013-07-17 04:54:00
541197 2016-07-27 04:21:00
192153 2012-11-30 17:27:00
28557  2011-08-06 22:50:00
20917  2011-09-08 02:17:00
438044 2015-07-19 03:13:00
553333 2016-09-03 15:13:00
303484 2014-02-26 09:17:00
137771 2012-04-16 14:57:00
221043 2013-03-30 13:27:00
227352 2013-04-25 10:28:00
576245 2016-11-28 06:51:00
74077  2010-12-09 05:22:00
120434 2012-01-29 23:50:00
540187 2016-07-23 16:00:00
601992 2017-04-14 11:19:00
649160 2017-09-20 12:19:00
293949 2014-01-18 20:50:00
552536 2016-09-06 22:09:00
500239 2016-03-03 06:20:00
602906 2017-04-15 19:20:00
194226 2012-12-09 00:20:00
489154 2016-01-21 15:52:00
89892  2010-09-14 07:52:00
184890 2012-10-29 11:33:00
539577 2016-07-20 23:36:00
546853 2016-08-14 07:09:00
23492  2011-08-27 17:55:00
355606 2014-09-15 23:22:00
322072 2014-05-11 20:26:00
319533 2014-05-02 04:44:00
208634 2013-02-07 05:21:00
633844 2017-07-30 18:41:00
219394 2013-03-23 08:48:00
51663  2011-04-02 11:37:00
550327 2016-08-25 14:15:00
368722 2014-10-30 22:46:00
129493 2012-03-09 18:23:00
515620 2016-04-27 04:55:00
312734 2014-04-06 02:13:00
337111 2014-07-09 18:39:00
384257 2015-01-01 05:23:00
393295 2015-02-04 02:50:00
4943   2011-10-17 18:53:00
520496 2016-05-16 06:26:00
191304 2012-11-26 19:28:00
201855 2013-01-09 08:28:00
514047 2016-04-24 11:51:00
439543 2015-07-24 18:55:00
377135 2014-12-01 21:56:00

In [ ]:
%debug

> /Users/emilygeller/ds/metis/metisgh/Geller_Metis/Project 5/pandas/_libs/tslib.pyx(3691)pandas._libs.tslib.array_strptime (pandas/_libs/tslib.c:63778)()

ipdb> arg
*** NameError: name 'arg' is not defined
ipdb> print(arg)
*** NameError: name 'arg' is not defined
ipdb> print(format)
<built-in function format>
ipdb> print(tslib)
*** NameError: name 'tslib' is not defined
--KeyboardInterrupt--

In [15]:
firecalls.sample(2000).groupby('Datetime').count()

Empty DataFrame
Columns: [Address, Type, Latitude, Longitude, Report Location, Incident Number]
Index: []

In [16]:
firecalls.head()

,Address,Type,Datetime,Latitude,Longitude,Report Location,Incident Number
1,6900 37th Av S,Medic Response,NaT,47.540683,-122.286131,"(47.540683, -122.286131)",F110104166
2,N 50th St / Stone Way N,Aid Response,NaT,47.665034,-122.340207,"(47.665034, -122.340207)",F110104164
3,E John St / E Olive Way,Aid Response,NaT,47.619575,-122.324257,"(47.619575, -122.324257)",F110104165
4,611 12th Av S,Aid Response,NaT,47.597406,-122.317228,"(47.597406, -122.317228)",F110104162
5,4545 42nd Av Sw,Automatic Medical Alarm,NaT,47.562472,-122.385455,"(47.562472, -122.385455)",F110104161